# Generated by Django 4.2 on 2023-04-12 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_film'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
